<?php

namespace Grav\Plugin;

use Grav\Common\Plugin;
use Grav\Plugin\FtpSync\SyncManager;
use RocketTheme\Toolbox\Event\Event;

/**
 * FTP Sync
 *
 * Dedicated Admin Panel page to sync user/pages + the active theme between
 * local (DDEV) and hosting over FTP/FTPS. Diff is based on mtime+size (see
 * DiffEngine), with automatic backup before overwriting; conflicts must be
 * resolved manually. The whole feature only works when detected as a local
 * environment, unless force_allow_remote is enabled in the config — on a
 * live hosting deployment of this same plugin, every task refuses to run.
 */
class FTPSyncPlugin extends Plugin
{
    public static function getSubscribedEvents()
    {
        return [
            'onPluginsInitialized' => ['onPluginsInitialized', 0],
        ];
    }

    public function onPluginsInitialized(): void
    {
        $this->registerAutoload();

        if (!$this->isAdmin()) {
            return;
        }

        $this->enable([
            'onAdminMenu' => ['onAdminMenu', 0],
            'onAdminTwigTemplatePaths' => ['onAdminTwigTemplatePaths', 0],
            'onAdminTaskExecute' => ['onAdminTaskExecute', 0],
            'onTwigInitialized' => ['onTwigInitialized', 0],
            'onOutputGenerated' => ['onOutputGenerated', 0],
        ]);
    }

    /**
     * Grav's own "/admin/plugins/ftp-sync" config page (host/username/
     * password fields) is generated by admin-classic straight from
     * blueprints.yaml — there's no template of ours to gate like
     * admin/templates/ftp-sync.html.twig. Instead of fighting Grav's
     * internal Blueprint-instance caching to mutate the form server-side,
     * inject a notice + a small script that disables every field the
     * moment the page loads, same idea as admin-quick-menu/easy-content-
     * manager's onOutputGenerated markup injection elsewhere in this repo.
     */
    public function onOutputGenerated(): void
    {
        $admin = $this->grav['admin'] ?? null;
        if (!$admin || $admin->location !== 'plugins' || $admin->route !== 'ftp-sync') {
            return;
        }
        if ($this->isEnabled()) {
            return;
        }

        $output = $this->grav->output;
        if (strpos($output, '</body>') === false) {
            return;
        }

        $injected = <<<'HTML'
<script>
(function () {
    document.addEventListener('DOMContentLoaded', function () {
        var form = document.getElementById('blueprints');
        if (!form) { return; }

        var notice = document.createElement('div');
        notice.className = 'notices error';
        notice.style.margin = '1.5rem 2rem';
        notice.style.textAlign = 'center';
        notice.style.fontSize = '1.2rem';
        notice.innerHTML = '<p><i class="fa fa-exclamation-triangle"></i> <b>Plugin not work on live site, only local host.</b></p>';
        form.parentNode.insertBefore(notice, form);

        form.querySelectorAll('input, select, textarea, button').forEach(function (el) {
            el.disabled = true;
        });

        var saveBtn = document.querySelector('button[form="blueprints"]');
        if (saveBtn) { saveBtn.disabled = true; }
    });
})();
</script>
HTML;

        $this->grav->output = str_replace('</body>', $injected . "\n</body>", $output);
    }

    public function onTwigInitialized(): void
    {
        $this->grav['twig']->twig()->addFunction(
            new \Twig\TwigFunction('ftp_sync_is_local', [$this, 'isLocalEnvironment'])
        );
        $this->grav['twig']->twig()->addFunction(
            new \Twig\TwigFunction('ftp_sync_is_enabled', [$this, 'isEnabled'])
        );
        $this->grav['twig']->twig()->addFunction(
            new \Twig\TwigFunction('ftp_sync_backup_path', [$this, 'backupPath'])
        );
    }

    /** Đường dẫn thư mục backup, tương đối so với gốc project (để copy dán vào File Explorer). */
    public function backupPath(): string
    {
        return 'user/data/ftp-sync/backups';
    }

    private function registerAutoload(): void
    {
        spl_autoload_register(function (string $class): void {
            $prefix = 'Grav\\Plugin\\FtpSync\\';
            if (strncmp($class, $prefix, strlen($prefix)) !== 0) {
                return;
            }
            $file = __DIR__ . '/classes/' . substr($class, strlen($prefix)) . '.php';
            if (is_file($file)) {
                require $file;
            }
        });
    }

    /**
     * Hides the "FTP Sync" nav item entirely on a live hosting deployment
     * (not local, force_allow_remote not set) — the page still exists and
     * is reachable by direct URL for anyone who knows it, but the sidebar
     * never advertises a feature that guardRequest() will refuse anyway.
     */
    public function onAdminMenu(): void
    {
        if (!$this->canManage() || !$this->isEnabled()) {
            return;
        }

        $this->grav['twig']->plugins_hooked_nav['FTP Sync'] = [
            'route' => 'ftp-sync',
            'icon' => 'fa-exchange',
            'authorize' => ['admin.super'],
            'priority' => 90,
        ];
    }

    public function onAdminTwigTemplatePaths(Event $event): void
    {
        $paths = $event['paths'];
        $paths[] = __DIR__ . '/admin/templates';
        $event['paths'] = $paths;
    }

    public function onAdminTaskExecute(Event $event): void
    {
        $controller = $event['controller'];
        $task = $controller->task ?? '';

        if ($task === 'ftpsynccheckdiff') {
            $event->stopPropagation();
            $this->handleCheckDiff($controller->post ?? []);
        } elseif ($task === 'ftpsyncsyncstart') {
            $event->stopPropagation();
            $this->handleSyncStart($controller->post ?? []);
        } elseif ($task === 'ftpsyncsyncstep') {
            $event->stopPropagation();
            $this->handleSyncStep($controller->post ?? []);
        } elseif ($task === 'ftpsyncpushstart') {
            $event->stopPropagation();
            $this->handlePushStart($controller->post ?? []);
        } elseif ($task === 'ftpsyncpushstep') {
            $event->stopPropagation();
            $this->handlePushStep($controller->post ?? []);
        } elseif ($task === 'ftpsyncfulldeploystart') {
            $event->stopPropagation();
            $this->handleFullDeployStart($controller->post ?? []);
        } elseif ($task === 'ftpsyncfulldeploystep') {
            $event->stopPropagation();
            $this->handleFullDeployStep($controller->post ?? []);
        } elseif ($task === 'ftpsyncfulldeploymarksynced') {
            $event->stopPropagation();
            $this->handleFullDeployMarkSynced();
        } elseif ($task === 'ftpsyncfulldeploycancel') {
            $event->stopPropagation();
            $this->handleFullDeployCancel($controller->post ?? []);
        } elseif ($task === 'ftpsynclistbackups') {
            $event->stopPropagation();
            $this->handleListBackups();
        } elseif ($task === 'ftpsyncdeletebackup') {
            $event->stopPropagation();
            $this->handleDeleteBackup($controller->post ?? []);
        }
    }

    private function handleCheckDiff(array $post): void
    {
        if (!$this->guardRequest()) {
            return;
        }

        $kinds = array_values((array) ($post['kinds'] ?? []));

        try {
            $result = $this->syncManager()->checkDiff($kinds);
            $this->grav['admin']->json_response = ['status' => 'success'] + $result;
        } catch (\Throwable $e) {
            $this->jsonError($e->getMessage());
        }
    }

    /** Bước 1/2 của "Sync now": xây hàng đợi thao tác, trả về job_id + tổng số để UI vẽ progress bar. */
    private function handleSyncStart(array $post): void
    {
        if (!$this->guardRequest()) {
            return;
        }

        $resolutions = (array) ($post['resolutions'] ?? []);

        try {
            $result = $this->syncManager()->startSyncJob($resolutions);
            $this->grav['admin']->json_response = ['status' => 'success'] + $result;
        } catch (\Throwable $e) {
            $this->jsonError($e->getMessage());
        }
    }

    /** Bước 2/2: xử lý 1 batch của job "Sync now" — UI gọi lặp lại tới khi finished=true. */
    private function handleSyncStep(array $post): void
    {
        if (!$this->guardRequest()) {
            return;
        }

        $jobId = (string) ($post['job_id'] ?? '');

        try {
            $result = $this->syncManager()->stepSyncJob($jobId);
            $this->grav['admin']->json_response = ['status' => 'success'] + $result;
        } catch (\Throwable $e) {
            $this->jsonError($e->getMessage());
        }
    }

    /**
     * Confirmation token the client sends after the user clicks "Yes" in the
     * modal — checked again on the server to make sure the request actually
     * went through the UI confirmation step, rather than calling the task
     * directly.
     */
    private const FORCE_PUSH_CONFIRM_PHRASE = 'CONFIRMED';

    /** Bước 1/2 của "Replace local sync to hosting" / "Full deploy to hosting": xây hàng đợi xoá+upload. */
    private function handlePushStart(array $post): void
    {
        if (!$this->guardRequest()) {
            return;
        }

        $confirm = trim((string) ($post['confirm'] ?? ''));
        if ($confirm !== self::FORCE_PUSH_CONFIRM_PHRASE) {
            $this->jsonError('Confirmation mismatch — upload cancelled for safety.');
            return;
        }

        $kinds = array_values((array) ($post['kinds'] ?? []));

        try {
            $result = $this->syncManager()->startPushJob($kinds);
            $this->grav['admin']->json_response = ['status' => 'success'] + $result;
        } catch (\Throwable $e) {
            $this->jsonError($e->getMessage());
        }
    }

    /** Bước 2/2: xử lý 1 batch của job push — UI gọi lặp lại tới khi finished=true. */
    private function handlePushStep(array $post): void
    {
        if (!$this->guardRequest()) {
            return;
        }

        $jobId = (string) ($post['job_id'] ?? '');

        try {
            $result = $this->syncManager()->stepPushJob($jobId);
            $this->grav['admin']->json_response = ['status' => 'success'] + $result;
        } catch (\Throwable $e) {
            $this->jsonError($e->getMessage());
        }
    }

    /**
     * Bước 1/2 của "Full deploy" — CHỈ nén site thành 1 file .zip local,
     * không xoá và không upload gì lên hosting (người dùng tự làm 2 việc
     * đó thủ công), nên không cần xác nhận nguy hiểm như handlePushStart().
     */
    private function handleFullDeployStart(array $post): void
    {
        if (!$this->guardRequest()) {
            return;
        }

        try {
            $result = $this->syncManager()->startFullDeployJob();
            $this->grav['admin']->json_response = ['status' => 'success'] + $result;
        } catch (\Throwable $e) {
            $this->jsonError($e->getMessage());
        }
    }

    /** Bước 2/2: xử lý 1 batch nén của job full-deploy — UI gọi lặp lại tới khi finished=true. */
    private function handleFullDeployStep(array $post): void
    {
        if (!$this->guardRequest()) {
            return;
        }

        $jobId = (string) ($post['job_id'] ?? '');

        try {
            $result = $this->syncManager()->stepFullDeployJob($jobId);
            $this->grav['admin']->json_response = ['status' => 'success'] + $result;
        } catch (\Throwable $e) {
            $this->jsonError($e->getMessage());
        }
    }

    /** Nút "Cancel compressing": huỷ job full-deploy đang nén dở và xoá file .zip tạm. */
    private function handleFullDeployCancel(array $post): void
    {
        if (!$this->guardRequest()) {
            return;
        }

        $jobId = (string) ($post['job_id'] ?? '');

        try {
            $this->syncManager()->cancelFullDeployJob($jobId);
            $this->grav['admin']->json_response = ['status' => 'success'];
        } catch (\Throwable $e) {
            $this->jsonError($e->getMessage());
        }
    }

    /**
     * Gọi sau khi người dùng đã tự tay upload + giải nén zip "Full deploy"
     * lên hosting — đọc mtime/size thật trên hosting qua FTP (không
     * upload/download gì) và lưu lại làm baseline cho phần "Check
     * differences" theo dõi.
     */
    private function handleFullDeployMarkSynced(): void
    {
        if (!$this->guardRequest()) {
            return;
        }

        try {
            $result = $this->syncManager()->markFullDeploySynced();
            $this->grav['admin']->json_response = ['status' => 'success'] + $result;
        } catch (\Throwable $e) {
            $this->jsonError($e->getMessage());
        }
    }

    private function handleListBackups(): void
    {
        if (!$this->guardRequest()) {
            return;
        }

        try {
            $backups = $this->syncManager()->listBackups();
            $this->grav['admin']->json_response = ['status' => 'success', 'backups' => $backups];
        } catch (\Throwable $e) {
            $this->jsonError($e->getMessage());
        }
    }

    private function handleDeleteBackup(array $post): void
    {
        if (!$this->guardRequest()) {
            return;
        }

        $name = (string) ($post['name'] ?? '');

        try {
            $this->syncManager()->deleteBackup($name);
            $this->grav['admin']->json_response = ['status' => 'success'];
        } catch (\Throwable $e) {
            $this->jsonError($e->getMessage());
        }
    }

    /**
     * Common gate for every task: must be an authorized admin AND the
     * plugin must be "enabled" (local environment, or force_allow_remote).
     * On a live hosting copy of this plugin, every single task refuses to
     * run — the FTP credentials are never exercised from the production
     * server itself.
     */
    private function guardRequest(): bool
    {
        if (!$this->canManage()) {
            $this->jsonError('Not authorized.');
            return false;
        }

        if (!$this->isEnabled()) {
            $this->jsonError('FTP Sync is disabled: this is not a local development environment.');
            return false;
        }

        return true;
    }

    private function syncManager(): SyncManager
    {
        $config = (array) $this->config->get('plugins.ftp-sync');
        // The theme to sync is ALWAYS the site's active theme
        // (system.pages.theme), never configured manually — change the
        // active theme anywhere, the plugin follows automatically.
        $config['active_theme'] = (string) $this->config->get('system.pages.theme', '');
        return new SyncManager($config, DATA_DIR . 'ftp-sync');
    }

    private function jsonError(string $message): void
    {
        $this->grav['admin']->json_response = ['status' => 'error', 'message' => $message];
    }

    /** Detects local by checking for a .ddev/ folder at the webroot. */
    public function isLocalEnvironment(): bool
    {
        return is_dir(GRAV_ROOT . '/.ddev');
    }

    /** Whether the whole plugin is allowed to run at all: local, or explicitly forced on. */
    public function isEnabled(): bool
    {
        return $this->isLocalEnvironment() || (bool) $this->config->get('plugins.ftp-sync.force_allow_remote', false);
    }

    private function canManage(): bool
    {
        $user = $this->grav['user'] ?? null;
        if (!$user || !$user->authenticated) {
            return false;
        }
        return $user->authorize('admin.super') === true;
    }
}
